# Generated by Django 3.1.1 on 2020-09-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhospital', '0003_auto_20200906_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='date_hour',
            new_name='date',
        ),
    ]
