# Generated by Django 3.1.1 on 2020-09-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhospital', '0004_auto_20200906_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='observations',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
    ]
