# Generated by Django 3.1.1 on 2020-09-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhospital', '0007_auto_20200907_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='observations',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
